on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'  # Or specify the version you're using

      - name: Install required R packages
        run: |
          R -e "install.packages(c('knitr', 'rmarkdown', 'rprojroot', 'dplyr', 'tidyverse', 'ggplot2', 'ggpmisc', 'MetBrewer', 'stringr', 'FactoMineR', 'factoextra', 'pheatmap', 'lubridate', 'lme4', 'broom', 'kableExtra', 'scales'))"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: true

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}